version: '3.3'
services:
  cinema-app:
#    image: 'com.example/cinema:latest'
    image: 'ilka/ilka_images_repository:cinema-app'
    container_name: cinema
    depends_on:
      - postgre-db
    ports:
      - "8080:8080"
  postgre-db:
    image: postgres
    container_name: postgre-db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cinema
    volumes:
      - pgvol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8000:80"
    depends_on:
      - postgre-db

volumes:
  pgvol:
  pgadmin:
